name: Another
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Changes
    types: [completed]
  push:

jobs:
  Detect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Debug
        env:
          EFFECTIVE_SHA: ${{ github.head_sha || github.sha }}
          SHA: ${{ github.sha }}
          HEAD_SHA: ${{ github.head_sha }}
          CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$EFFECTIVE_SHA"
          echo "$SHA"
          echo "$HEAD_SHA"
          echo "$GITHUB_REF"
          echo "$CONTEXT"

