name: Another
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Changes
    types: [completed]

jobs:
  env:
    EFFECTIVE_SHA: ${{ github.event.workflow_run.head_sha | github.sha }}

  Success:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Sha
          MAIN_SHA: ${{ github.sha }}
          WORKFLOW_SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          echo "SHA from workflow trigger: "
          echo "$EFFECTIVE_SHA"

          echo "SHA from main: "
          echo "$MAIN_SHA"

          echo "SHA from worfklow: "
          echo "$WORKFLOW_SHA"
  
  Success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Effective Sha
        run: |
          echo "SHA from workflow trigger: "
          echo "$EFFECTIVE_SHA"
