name: Another
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Changes
    types: [completed]
  push:

jobs:
  Detect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Debug
        env:
          CONTEXT: ${{ toJson(github) }}
          WORKFLOW: ${{ toJson(github.event.workflow_run) }}
        run: |
          echo "$CONTEXT"
          echo "$WORKFLOW"

