name: Another
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Changes
    types: [completed]
  push:

jobs:
  Detect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Debug
        env:
          HEAD_SHA: ${{ toJson(github).head_sha }}
          SHA: ${{ toJson(github).sha }}
        run: |
          echo "$HEAD_SHA"
          echo "$SHA"
