name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Changes
    types: [completed]

env:
  EFFECTIVE_SHA: ${{ github.event.workflow_run.head_sha || github.sha }}

jobs:
  Success:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Sha
        env:
            MAIN_SHA: ${{ github.sha }}
            WORKFLOW_SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          echo "Effective Sha"
          echo "$EFFECTIVE_SHA"

          echo "SHA from main: "
          echo "$MAIN_SHA"

          echo "SHA from worfklow: "
          echo "$WORKFLOW_SHA"
  
  Effective:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Effective Sha
        run: |
          echo "Effective SHA"
          echo "$EFFECTIVE_SHA"
