name: Another
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Changes
    types: [completed]

jobs:
  Context:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Debug
        env:
          WORKFLOW: ${{ toJson(github.event.workflow_run) }}
        run: |
          echo "$WORKFLOW"

