name: Changes
on: ["push"]

jobs:
  Detect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Ref
        id: ref
        run: |
          if [[ $before == "0000000000000000000000000000000000000000" ]]; then
            echo "::set-output name=before::$(git merge-base ${{ github.event.repository.default_branch }} HEAD)"
          else
            echo "::set-output name=before::${before}"
          fi
        env:
          before: ${{ github.event.before }}
      - name: Debug
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
