name: Test
on: ["push"]

jobs:
  Detect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          exit 1 
          # (( RANDOM%2 == 0 )) && exit 0 || exit 1
