name: Changes
on: ["push"]

jobs:
  Detect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Ref
        id: ref
        run: |
          git fetch origin main
          git fetch origin HEAD
          git merge-base origin/main HEAD
          git log
          echo "::set-output name=before::$(git merge-base origin/${{ github.event.repository.default_branch }} HEAD)"
        env:
          before: ${{ github.event.before }}
      - name: Debug
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
