name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test
    types: [completed]

jobs:
  env:
    effective_sha: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_sha || github.sha }}
  Effective:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      effective_sha : $effective_sha
    steps:
      - id: sha
        run: echo $effective_sha

  Print:
    needs: effective
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Effective Sha
        run:  echo ${{needs.effective.outputs.effective_sha}} 
