name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test
    types: [completed]

jobs:
  Effective:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      effective_sha: ${{ steps.sha.outputs.value }}
    env:
      EFFECTIVE_SHA: "${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_sha || github.sha }}"
    steps:
      - id: sha
        run: echo "::set-output name=value::${EFFECTIVE_SHA}"

  Print:
    needs: effective
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Effective Sha
        run:  echo ${{needs.effective.outputs.effective_sha}} 
